package com.gobase.component.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IBaseMapper<E, T> {
    /**
     * 
     * <br/>Description:通用模板类
     * <p>Author:zcliu/刘子萃</p>
     * @param example
     * @return
     */
    long countByExample(E example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_category
     *
     * @mbg.generated Wed Jun 12 15:49:36 CST 2019
     */
    int deleteByExample(E example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_category
     *
     * @mbg.generated Wed Jun 12 15:49:36 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_category
     *
     * @mbg.generated Wed Jun 12 15:49:36 CST 2019
     */
    int insert(T record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_category
     *
     * @mbg.generated Wed Jun 12 15:49:36 CST 2019
     */
    int insertSelective(T record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_category
     *
     * @mbg.generated Wed Jun 12 15:49:36 CST 2019
     */
    List<T> selectByExample(E example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_category
     *
     * @mbg.generated Wed Jun 12 15:49:36 CST 2019
     */
    T selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_category
     *
     * @mbg.generated Wed Jun 12 15:49:36 CST 2019
     */
    int updateByExampleSelective(@Param("record") T record, @Param("example") E example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_category
     *
     * @mbg.generated Wed Jun 12 15:49:36 CST 2019
     */
    int updateByExample(@Param("record") T record, @Param("example") E example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_category
     *
     * @mbg.generated Wed Jun 12 15:49:36 CST 2019
     */
    int updateByPrimaryKeySelective(T record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_category
     *
     * @mbg.generated Wed Jun 12 15:49:36 CST 2019
     */
    int updateByPrimaryKey(T record);
}