package com.gobase.component.bean.mall.region;

public class Region {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column region.id
     *
     * @mbg.generated Thu Jul 18 22:16:42 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column region.name
     *
     * @mbg.generated Thu Jul 18 22:16:42 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column region.parent_id
     *
     * @mbg.generated Thu Jul 18 22:16:42 CST 2019
     */
    private Integer parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column region.level
     *
     * @mbg.generated Thu Jul 18 22:16:42 CST 2019
     */
    private Byte level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column region.status
     *
     * @mbg.generated Thu Jul 18 22:16:42 CST 2019
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column region.sort
     *
     * @mbg.generated Thu Jul 18 22:16:42 CST 2019
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column region.gb_code
     *
     * @mbg.generated Thu Jul 18 22:16:42 CST 2019
     */
    private Integer gbCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column region.full_name
     *
     * @mbg.generated Thu Jul 18 22:16:42 CST 2019
     */
    private String fullName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column region.id
     *
     * @return the value of region.id
     *
     * @mbg.generated Thu Jul 18 22:16:42 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column region.id
     *
     * @param id the value for region.id
     *
     * @mbg.generated Thu Jul 18 22:16:42 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column region.name
     *
     * @return the value of region.name
     *
     * @mbg.generated Thu Jul 18 22:16:42 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column region.name
     *
     * @param name the value for region.name
     *
     * @mbg.generated Thu Jul 18 22:16:42 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column region.parent_id
     *
     * @return the value of region.parent_id
     *
     * @mbg.generated Thu Jul 18 22:16:42 CST 2019
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column region.parent_id
     *
     * @param parentId the value for region.parent_id
     *
     * @mbg.generated Thu Jul 18 22:16:42 CST 2019
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column region.level
     *
     * @return the value of region.level
     *
     * @mbg.generated Thu Jul 18 22:16:42 CST 2019
     */
    public Byte getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column region.level
     *
     * @param level the value for region.level
     *
     * @mbg.generated Thu Jul 18 22:16:42 CST 2019
     */
    public void setLevel(Byte level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column region.status
     *
     * @return the value of region.status
     *
     * @mbg.generated Thu Jul 18 22:16:42 CST 2019
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column region.status
     *
     * @param status the value for region.status
     *
     * @mbg.generated Thu Jul 18 22:16:42 CST 2019
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column region.sort
     *
     * @return the value of region.sort
     *
     * @mbg.generated Thu Jul 18 22:16:42 CST 2019
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column region.sort
     *
     * @param sort the value for region.sort
     *
     * @mbg.generated Thu Jul 18 22:16:42 CST 2019
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column region.gb_code
     *
     * @return the value of region.gb_code
     *
     * @mbg.generated Thu Jul 18 22:16:42 CST 2019
     */
    public Integer getGbCode() {
        return gbCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column region.gb_code
     *
     * @param gbCode the value for region.gb_code
     *
     * @mbg.generated Thu Jul 18 22:16:42 CST 2019
     */
    public void setGbCode(Integer gbCode) {
        this.gbCode = gbCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column region.full_name
     *
     * @return the value of region.full_name
     *
     * @mbg.generated Thu Jul 18 22:16:42 CST 2019
     */
    public String getFullName() {
        return fullName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column region.full_name
     *
     * @param fullName the value for region.full_name
     *
     * @mbg.generated Thu Jul 18 22:16:42 CST 2019
     */
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }
}