package com.gobase.component.bean.mall.user;

import java.util.Date;

public class UserAddress {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.id
     *
     * @mbg.generated Thu Jul 18 11:07:07 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.user_id
     *
     * @mbg.generated Thu Jul 18 11:07:07 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.province_id
     *
     * @mbg.generated Thu Jul 18 11:07:07 CST 2019
     */
    private Integer provinceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.city_id
     *
     * @mbg.generated Thu Jul 18 11:07:07 CST 2019
     */
    private Integer cityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.county_id
     *
     * @mbg.generated Thu Jul 18 11:07:07 CST 2019
     */
    private Integer countyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.address
     *
     * @mbg.generated Thu Jul 18 11:07:07 CST 2019
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.is_default
     *
     * @mbg.generated Thu Jul 18 11:07:07 CST 2019
     */
    private Integer isDefault;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.phone
     *
     * @mbg.generated Thu Jul 18 11:07:07 CST 2019
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.consignee
     *
     * @mbg.generated Thu Jul 18 11:07:07 CST 2019
     */
    private String consignee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.create_time
     *
     * @mbg.generated Thu Jul 18 11:07:07 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.update_time
     *
     * @mbg.generated Thu Jul 18 11:07:07 CST 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.id
     *
     * @return the value of user_address.id
     *
     * @mbg.generated Thu Jul 18 11:07:07 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.id
     *
     * @param id the value for user_address.id
     *
     * @mbg.generated Thu Jul 18 11:07:07 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.user_id
     *
     * @return the value of user_address.user_id
     *
     * @mbg.generated Thu Jul 18 11:07:07 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.user_id
     *
     * @param userId the value for user_address.user_id
     *
     * @mbg.generated Thu Jul 18 11:07:07 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.province_id
     *
     * @return the value of user_address.province_id
     *
     * @mbg.generated Thu Jul 18 11:07:07 CST 2019
     */
    public Integer getProvinceId() {
        return provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.province_id
     *
     * @param provinceId the value for user_address.province_id
     *
     * @mbg.generated Thu Jul 18 11:07:07 CST 2019
     */
    public void setProvinceId(Integer provinceId) {
        this.provinceId = provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.city_id
     *
     * @return the value of user_address.city_id
     *
     * @mbg.generated Thu Jul 18 11:07:07 CST 2019
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.city_id
     *
     * @param cityId the value for user_address.city_id
     *
     * @mbg.generated Thu Jul 18 11:07:07 CST 2019
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.county_id
     *
     * @return the value of user_address.county_id
     *
     * @mbg.generated Thu Jul 18 11:07:07 CST 2019
     */
    public Integer getCountyId() {
        return countyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.county_id
     *
     * @param countyId the value for user_address.county_id
     *
     * @mbg.generated Thu Jul 18 11:07:07 CST 2019
     */
    public void setCountyId(Integer countyId) {
        this.countyId = countyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.address
     *
     * @return the value of user_address.address
     *
     * @mbg.generated Thu Jul 18 11:07:07 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.address
     *
     * @param address the value for user_address.address
     *
     * @mbg.generated Thu Jul 18 11:07:07 CST 2019
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.is_default
     *
     * @return the value of user_address.is_default
     *
     * @mbg.generated Thu Jul 18 11:07:07 CST 2019
     */
    public Integer getIsDefault() {
        return isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.is_default
     *
     * @param isDefault the value for user_address.is_default
     *
     * @mbg.generated Thu Jul 18 11:07:07 CST 2019
     */
    public void setIsDefault(Integer isDefault) {
        this.isDefault = isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.phone
     *
     * @return the value of user_address.phone
     *
     * @mbg.generated Thu Jul 18 11:07:07 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.phone
     *
     * @param phone the value for user_address.phone
     *
     * @mbg.generated Thu Jul 18 11:07:07 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.consignee
     *
     * @return the value of user_address.consignee
     *
     * @mbg.generated Thu Jul 18 11:07:07 CST 2019
     */
    public String getConsignee() {
        return consignee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.consignee
     *
     * @param consignee the value for user_address.consignee
     *
     * @mbg.generated Thu Jul 18 11:07:07 CST 2019
     */
    public void setConsignee(String consignee) {
        this.consignee = consignee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.create_time
     *
     * @return the value of user_address.create_time
     *
     * @mbg.generated Thu Jul 18 11:07:07 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.create_time
     *
     * @param createTime the value for user_address.create_time
     *
     * @mbg.generated Thu Jul 18 11:07:07 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.update_time
     *
     * @return the value of user_address.update_time
     *
     * @mbg.generated Thu Jul 18 11:07:07 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.update_time
     *
     * @param updateTime the value for user_address.update_time
     *
     * @mbg.generated Thu Jul 18 11:07:07 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}