package com.gobase.component.bean.mall.goods;

public class GoodsCategory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_category.id
     *
     * @mbg.generated Tue Jun 11 21:21:21 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_category.code
     *
     * @mbg.generated Tue Jun 11 21:21:21 CST 2019
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_category.pcode
     *
     * @mbg.generated Tue Jun 11 21:21:21 CST 2019
     */
    private String pcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_category.name
     *
     * @mbg.generated Tue Jun 11 21:21:21 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_category.group_code
     *
     * @mbg.generated Tue Jun 11 21:21:21 CST 2019
     */
    private String groupCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_category.id
     *
     * @return the value of goods_category.id
     *
     * @mbg.generated Tue Jun 11 21:21:21 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_category.id
     *
     * @param id the value for goods_category.id
     *
     * @mbg.generated Tue Jun 11 21:21:21 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_category.code
     *
     * @return the value of goods_category.code
     *
     * @mbg.generated Tue Jun 11 21:21:21 CST 2019
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_category.code
     *
     * @param code the value for goods_category.code
     *
     * @mbg.generated Tue Jun 11 21:21:21 CST 2019
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_category.pcode
     *
     * @return the value of goods_category.pcode
     *
     * @mbg.generated Tue Jun 11 21:21:21 CST 2019
     */
    public String getPcode() {
        return pcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_category.pcode
     *
     * @param pcode the value for goods_category.pcode
     *
     * @mbg.generated Tue Jun 11 21:21:21 CST 2019
     */
    public void setPcode(String pcode) {
        this.pcode = pcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_category.name
     *
     * @return the value of goods_category.name
     *
     * @mbg.generated Tue Jun 11 21:21:21 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_category.name
     *
     * @param name the value for goods_category.name
     *
     * @mbg.generated Tue Jun 11 21:21:21 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_category.group_code
     *
     * @return the value of goods_category.group_code
     *
     * @mbg.generated Tue Jun 11 21:21:21 CST 2019
     */
    public String getGroupCode() {
        return groupCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_category.group_code
     *
     * @param groupCode the value for goods_category.group_code
     *
     * @mbg.generated Tue Jun 11 21:21:21 CST 2019
     */
    public void setGroupCode(String groupCode) {
        this.groupCode = groupCode;
    }
}