package com.gobase.component.bean.mall.shop;

import java.util.Date;
import java.util.List;

import com.gobase.component.bean.mall.goods.Goods;

public class ShopDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.id
     *
     * @mbg.generated Fri Jul 05 19:08:42 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.shop_name
     *
     * @mbg.generated Fri Jul 05 19:08:42 CST 2019
     */
    private String shopName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.license_no
     *
     * @mbg.generated Fri Jul 05 19:08:42 CST 2019
     */
    private String licenseNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.province_id
     *
     * @mbg.generated Fri Jul 05 19:08:42 CST 2019
     */
    private Integer provinceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.city_id
     *
     * @mbg.generated Fri Jul 05 19:08:42 CST 2019
     */
    private Integer cityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.pf_user_id
     *
     * @mbg.generated Fri Jul 05 19:08:42 CST 2019
     */
    private Integer pfUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.status
     *
     * @mbg.generated Fri Jul 05 19:08:42 CST 2019
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.create_time
     *
     * @mbg.generated Fri Jul 05 19:08:42 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.update_time
     *
     * @mbg.generated Fri Jul 05 19:08:42 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.logo_url
     *
     * @mbg.generated Fri Jul 05 19:08:42 CST 2019
     */
    private String logoUrl;
    
    private List<Goods> goodsList;
    
    private long saleCount;
    
    public long getSaleCount() {
		return saleCount;
	}
    
	public void setSaleCount(long saleCount) {
		this.saleCount = saleCount;
	}
	
    public List<Goods> getGoodsList() {
		return goodsList;
	}
    
	public void setGoodsList(List<Goods> goodsList) {
		this.goodsList = goodsList;
	}
	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.id
     *
     * @return the value of shop.id
     *
     * @mbg.generated Fri Jul 05 19:08:42 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.id
     *
     * @param id the value for shop.id
     *
     * @mbg.generated Fri Jul 05 19:08:42 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.shop_name
     *
     * @return the value of shop.shop_name
     *
     * @mbg.generated Fri Jul 05 19:08:42 CST 2019
     */
    public String getShopName() {
        return shopName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.shop_name
     *
     * @param shopName the value for shop.shop_name
     *
     * @mbg.generated Fri Jul 05 19:08:42 CST 2019
     */
    public void setShopName(String shopName) {
        this.shopName = shopName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.license_no
     *
     * @return the value of shop.license_no
     *
     * @mbg.generated Fri Jul 05 19:08:42 CST 2019
     */
    public String getLicenseNo() {
        return licenseNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.license_no
     *
     * @param licenseNo the value for shop.license_no
     *
     * @mbg.generated Fri Jul 05 19:08:42 CST 2019
     */
    public void setLicenseNo(String licenseNo) {
        this.licenseNo = licenseNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.province_id
     *
     * @return the value of shop.province_id
     *
     * @mbg.generated Fri Jul 05 19:08:42 CST 2019
     */
    public Integer getProvinceId() {
        return provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.province_id
     *
     * @param provinceId the value for shop.province_id
     *
     * @mbg.generated Fri Jul 05 19:08:42 CST 2019
     */
    public void setProvinceId(Integer provinceId) {
        this.provinceId = provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.city_id
     *
     * @return the value of shop.city_id
     *
     * @mbg.generated Fri Jul 05 19:08:42 CST 2019
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.city_id
     *
     * @param cityId the value for shop.city_id
     *
     * @mbg.generated Fri Jul 05 19:08:42 CST 2019
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.pf_user_id
     *
     * @return the value of shop.pf_user_id
     *
     * @mbg.generated Fri Jul 05 19:08:42 CST 2019
     */
    public Integer getPfUserId() {
        return pfUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.pf_user_id
     *
     * @param pfUserId the value for shop.pf_user_id
     *
     * @mbg.generated Fri Jul 05 19:08:42 CST 2019
     */
    public void setPfUserId(Integer pfUserId) {
        this.pfUserId = pfUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.status
     *
     * @return the value of shop.status
     *
     * @mbg.generated Fri Jul 05 19:08:42 CST 2019
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.status
     *
     * @param status the value for shop.status
     *
     * @mbg.generated Fri Jul 05 19:08:42 CST 2019
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.create_time
     *
     * @return the value of shop.create_time
     *
     * @mbg.generated Fri Jul 05 19:08:42 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.create_time
     *
     * @param createTime the value for shop.create_time
     *
     * @mbg.generated Fri Jul 05 19:08:42 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.update_time
     *
     * @return the value of shop.update_time
     *
     * @mbg.generated Fri Jul 05 19:08:42 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.update_time
     *
     * @param updateTime the value for shop.update_time
     *
     * @mbg.generated Fri Jul 05 19:08:42 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.logo_url
     *
     * @return the value of shop.logo_url
     *
     * @mbg.generated Fri Jul 05 19:08:42 CST 2019
     */
    public String getLogoUrl() {
        return logoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.logo_url
     *
     * @param logoUrl the value for shop.logo_url
     *
     * @mbg.generated Fri Jul 05 19:08:42 CST 2019
     */
    public void setLogoUrl(String logoUrl) {
        this.logoUrl = logoUrl;
    }
}