package com.gobase.component.bean.mall.shop;

import java.math.BigDecimal;
import java.util.Date;

public class ShopTradeRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_trade_record.id
     *
     * @mbg.generated Fri Jul 05 19:11:08 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_trade_record.source_id
     *
     * @mbg.generated Fri Jul 05 19:11:08 CST 2019
     */
    private Integer sourceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_trade_record.target_id
     *
     * @mbg.generated Fri Jul 05 19:11:08 CST 2019
     */
    private Integer targetId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_trade_record.amount
     *
     * @mbg.generated Fri Jul 05 19:11:08 CST 2019
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_trade_record.status
     *
     * @mbg.generated Fri Jul 05 19:11:08 CST 2019
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_trade_record.create_time
     *
     * @mbg.generated Fri Jul 05 19:11:08 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_trade_record.update_time
     *
     * @mbg.generated Fri Jul 05 19:11:08 CST 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_trade_record.id
     *
     * @return the value of shop_trade_record.id
     *
     * @mbg.generated Fri Jul 05 19:11:08 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_trade_record.id
     *
     * @param id the value for shop_trade_record.id
     *
     * @mbg.generated Fri Jul 05 19:11:08 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_trade_record.source_id
     *
     * @return the value of shop_trade_record.source_id
     *
     * @mbg.generated Fri Jul 05 19:11:08 CST 2019
     */
    public Integer getSourceId() {
        return sourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_trade_record.source_id
     *
     * @param sourceId the value for shop_trade_record.source_id
     *
     * @mbg.generated Fri Jul 05 19:11:08 CST 2019
     */
    public void setSourceId(Integer sourceId) {
        this.sourceId = sourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_trade_record.target_id
     *
     * @return the value of shop_trade_record.target_id
     *
     * @mbg.generated Fri Jul 05 19:11:08 CST 2019
     */
    public Integer getTargetId() {
        return targetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_trade_record.target_id
     *
     * @param targetId the value for shop_trade_record.target_id
     *
     * @mbg.generated Fri Jul 05 19:11:08 CST 2019
     */
    public void setTargetId(Integer targetId) {
        this.targetId = targetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_trade_record.amount
     *
     * @return the value of shop_trade_record.amount
     *
     * @mbg.generated Fri Jul 05 19:11:08 CST 2019
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_trade_record.amount
     *
     * @param amount the value for shop_trade_record.amount
     *
     * @mbg.generated Fri Jul 05 19:11:08 CST 2019
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_trade_record.status
     *
     * @return the value of shop_trade_record.status
     *
     * @mbg.generated Fri Jul 05 19:11:08 CST 2019
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_trade_record.status
     *
     * @param status the value for shop_trade_record.status
     *
     * @mbg.generated Fri Jul 05 19:11:08 CST 2019
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_trade_record.create_time
     *
     * @return the value of shop_trade_record.create_time
     *
     * @mbg.generated Fri Jul 05 19:11:08 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_trade_record.create_time
     *
     * @param createTime the value for shop_trade_record.create_time
     *
     * @mbg.generated Fri Jul 05 19:11:08 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_trade_record.update_time
     *
     * @return the value of shop_trade_record.update_time
     *
     * @mbg.generated Fri Jul 05 19:11:08 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_trade_record.update_time
     *
     * @param updateTime the value for shop_trade_record.update_time
     *
     * @mbg.generated Fri Jul 05 19:11:08 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}