package com.gobase.component.bean.mall.shop;

import java.math.BigDecimal;
import java.util.Date;

public class ShopAccount {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_account.id
     *
     * @mbg.generated Fri Jul 05 19:11:08 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_account.shop_id
     *
     * @mbg.generated Fri Jul 05 19:11:08 CST 2019
     */
    private Integer shopId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_account.amount
     *
     * @mbg.generated Fri Jul 05 19:11:08 CST 2019
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_account.status
     *
     * @mbg.generated Fri Jul 05 19:11:08 CST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_account.create_time
     *
     * @mbg.generated Fri Jul 05 19:11:08 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_account.update_time
     *
     * @mbg.generated Fri Jul 05 19:11:08 CST 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_account.id
     *
     * @return the value of shop_account.id
     *
     * @mbg.generated Fri Jul 05 19:11:08 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_account.id
     *
     * @param id the value for shop_account.id
     *
     * @mbg.generated Fri Jul 05 19:11:08 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_account.shop_id
     *
     * @return the value of shop_account.shop_id
     *
     * @mbg.generated Fri Jul 05 19:11:08 CST 2019
     */
    public Integer getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_account.shop_id
     *
     * @param shopId the value for shop_account.shop_id
     *
     * @mbg.generated Fri Jul 05 19:11:08 CST 2019
     */
    public void setShopId(Integer shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_account.amount
     *
     * @return the value of shop_account.amount
     *
     * @mbg.generated Fri Jul 05 19:11:08 CST 2019
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_account.amount
     *
     * @param amount the value for shop_account.amount
     *
     * @mbg.generated Fri Jul 05 19:11:08 CST 2019
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_account.status
     *
     * @return the value of shop_account.status
     *
     * @mbg.generated Fri Jul 05 19:11:08 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_account.status
     *
     * @param status the value for shop_account.status
     *
     * @mbg.generated Fri Jul 05 19:11:08 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_account.create_time
     *
     * @return the value of shop_account.create_time
     *
     * @mbg.generated Fri Jul 05 19:11:08 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_account.create_time
     *
     * @param createTime the value for shop_account.create_time
     *
     * @mbg.generated Fri Jul 05 19:11:08 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_account.update_time
     *
     * @return the value of shop_account.update_time
     *
     * @mbg.generated Fri Jul 05 19:11:08 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_account.update_time
     *
     * @param updateTime the value for shop_account.update_time
     *
     * @mbg.generated Fri Jul 05 19:11:08 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}