package com.gobase.component.bean.mall.order;

import java.util.Date;

public class Order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.id
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_id
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.user_id
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.sku_num
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    private Integer skuNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.sku_price
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    private Double skuPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.sku_name
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    private String skuName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.sku_logo
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    private String skuLogo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.region_id
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    private Integer regionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.attr_info
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    private String attrInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.status
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.goods_id
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    private String goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.sku_id
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    private String skuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.remark
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.address
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.pay_credit_img
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    private String payCreditImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.create_time
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.kuaidi_name
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    private String kuaidiName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.kuaidi_order
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    private String kuaidiOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.kuaidi_price
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    private Double kuaidiPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.manjian_price
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    private Double manjianPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.user_coupons_id
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    private Integer userCouponsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.coupons_price
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    private Double couponsPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.coupons_type
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    private Integer couponsType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.reduce_intr_rate
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    private Double reduceIntrRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.deliver_time
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    private Date deliverTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.id
     *
     * @return the value of order.id
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.id
     *
     * @param id the value for order.id
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_id
     *
     * @return the value of order.order_id
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.order_id
     *
     * @param orderId the value for order.order_id
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.user_id
     *
     * @return the value of order.user_id
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.user_id
     *
     * @param userId the value for order.user_id
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.sku_num
     *
     * @return the value of order.sku_num
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    public Integer getSkuNum() {
        return skuNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.sku_num
     *
     * @param skuNum the value for order.sku_num
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    public void setSkuNum(Integer skuNum) {
        this.skuNum = skuNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.sku_price
     *
     * @return the value of order.sku_price
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    public Double getSkuPrice() {
        return skuPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.sku_price
     *
     * @param skuPrice the value for order.sku_price
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    public void setSkuPrice(Double skuPrice) {
        this.skuPrice = skuPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.sku_name
     *
     * @return the value of order.sku_name
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    public String getSkuName() {
        return skuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.sku_name
     *
     * @param skuName the value for order.sku_name
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    public void setSkuName(String skuName) {
        this.skuName = skuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.sku_logo
     *
     * @return the value of order.sku_logo
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    public String getSkuLogo() {
        return skuLogo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.sku_logo
     *
     * @param skuLogo the value for order.sku_logo
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    public void setSkuLogo(String skuLogo) {
        this.skuLogo = skuLogo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.region_id
     *
     * @return the value of order.region_id
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    public Integer getRegionId() {
        return regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.region_id
     *
     * @param regionId the value for order.region_id
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    public void setRegionId(Integer regionId) {
        this.regionId = regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.attr_info
     *
     * @return the value of order.attr_info
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    public String getAttrInfo() {
        return attrInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.attr_info
     *
     * @param attrInfo the value for order.attr_info
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    public void setAttrInfo(String attrInfo) {
        this.attrInfo = attrInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.status
     *
     * @return the value of order.status
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.status
     *
     * @param status the value for order.status
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.goods_id
     *
     * @return the value of order.goods_id
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    public String getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.goods_id
     *
     * @param goodsId the value for order.goods_id
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    public void setGoodsId(String goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.sku_id
     *
     * @return the value of order.sku_id
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    public String getSkuId() {
        return skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.sku_id
     *
     * @param skuId the value for order.sku_id
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    public void setSkuId(String skuId) {
        this.skuId = skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.remark
     *
     * @return the value of order.remark
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.remark
     *
     * @param remark the value for order.remark
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.address
     *
     * @return the value of order.address
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.address
     *
     * @param address the value for order.address
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.pay_credit_img
     *
     * @return the value of order.pay_credit_img
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    public String getPayCreditImg() {
        return payCreditImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.pay_credit_img
     *
     * @param payCreditImg the value for order.pay_credit_img
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    public void setPayCreditImg(String payCreditImg) {
        this.payCreditImg = payCreditImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.create_time
     *
     * @return the value of order.create_time
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.create_time
     *
     * @param createTime the value for order.create_time
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.kuaidi_name
     *
     * @return the value of order.kuaidi_name
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    public String getKuaidiName() {
        return kuaidiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.kuaidi_name
     *
     * @param kuaidiName the value for order.kuaidi_name
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    public void setKuaidiName(String kuaidiName) {
        this.kuaidiName = kuaidiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.kuaidi_order
     *
     * @return the value of order.kuaidi_order
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    public String getKuaidiOrder() {
        return kuaidiOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.kuaidi_order
     *
     * @param kuaidiOrder the value for order.kuaidi_order
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    public void setKuaidiOrder(String kuaidiOrder) {
        this.kuaidiOrder = kuaidiOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.kuaidi_price
     *
     * @return the value of order.kuaidi_price
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    public Double getKuaidiPrice() {
        return kuaidiPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.kuaidi_price
     *
     * @param kuaidiPrice the value for order.kuaidi_price
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    public void setKuaidiPrice(Double kuaidiPrice) {
        this.kuaidiPrice = kuaidiPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.manjian_price
     *
     * @return the value of order.manjian_price
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    public Double getManjianPrice() {
        return manjianPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.manjian_price
     *
     * @param manjianPrice the value for order.manjian_price
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    public void setManjianPrice(Double manjianPrice) {
        this.manjianPrice = manjianPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.user_coupons_id
     *
     * @return the value of order.user_coupons_id
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    public Integer getUserCouponsId() {
        return userCouponsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.user_coupons_id
     *
     * @param userCouponsId the value for order.user_coupons_id
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    public void setUserCouponsId(Integer userCouponsId) {
        this.userCouponsId = userCouponsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.coupons_price
     *
     * @return the value of order.coupons_price
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    public Double getCouponsPrice() {
        return couponsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.coupons_price
     *
     * @param couponsPrice the value for order.coupons_price
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    public void setCouponsPrice(Double couponsPrice) {
        this.couponsPrice = couponsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.coupons_type
     *
     * @return the value of order.coupons_type
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    public Integer getCouponsType() {
        return couponsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.coupons_type
     *
     * @param couponsType the value for order.coupons_type
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    public void setCouponsType(Integer couponsType) {
        this.couponsType = couponsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.reduce_intr_rate
     *
     * @return the value of order.reduce_intr_rate
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    public Double getReduceIntrRate() {
        return reduceIntrRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.reduce_intr_rate
     *
     * @param reduceIntrRate the value for order.reduce_intr_rate
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    public void setReduceIntrRate(Double reduceIntrRate) {
        this.reduceIntrRate = reduceIntrRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.deliver_time
     *
     * @return the value of order.deliver_time
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    public Date getDeliverTime() {
        return deliverTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.deliver_time
     *
     * @param deliverTime the value for order.deliver_time
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    public void setDeliverTime(Date deliverTime) {
        this.deliverTime = deliverTime;
    }
}