package com.gobase.component.bean.mall.order;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class OrderExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    public OrderExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table order
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNull() {
            addCriterion("order_id is null");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNotNull() {
            addCriterion("order_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrderIdEqualTo(String value) {
            addCriterion("order_id =", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotEqualTo(String value) {
            addCriterion("order_id <>", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThan(String value) {
            addCriterion("order_id >", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThanOrEqualTo(String value) {
            addCriterion("order_id >=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThan(String value) {
            addCriterion("order_id <", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThanOrEqualTo(String value) {
            addCriterion("order_id <=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLike(String value) {
            addCriterion("order_id like", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotLike(String value) {
            addCriterion("order_id not like", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdIn(List<String> values) {
            addCriterion("order_id in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotIn(List<String> values) {
            addCriterion("order_id not in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdBetween(String value1, String value2) {
            addCriterion("order_id between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotBetween(String value1, String value2) {
            addCriterion("order_id not between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andSkuNumIsNull() {
            addCriterion("sku_num is null");
            return (Criteria) this;
        }

        public Criteria andSkuNumIsNotNull() {
            addCriterion("sku_num is not null");
            return (Criteria) this;
        }

        public Criteria andSkuNumEqualTo(Integer value) {
            addCriterion("sku_num =", value, "skuNum");
            return (Criteria) this;
        }

        public Criteria andSkuNumNotEqualTo(Integer value) {
            addCriterion("sku_num <>", value, "skuNum");
            return (Criteria) this;
        }

        public Criteria andSkuNumGreaterThan(Integer value) {
            addCriterion("sku_num >", value, "skuNum");
            return (Criteria) this;
        }

        public Criteria andSkuNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("sku_num >=", value, "skuNum");
            return (Criteria) this;
        }

        public Criteria andSkuNumLessThan(Integer value) {
            addCriterion("sku_num <", value, "skuNum");
            return (Criteria) this;
        }

        public Criteria andSkuNumLessThanOrEqualTo(Integer value) {
            addCriterion("sku_num <=", value, "skuNum");
            return (Criteria) this;
        }

        public Criteria andSkuNumIn(List<Integer> values) {
            addCriterion("sku_num in", values, "skuNum");
            return (Criteria) this;
        }

        public Criteria andSkuNumNotIn(List<Integer> values) {
            addCriterion("sku_num not in", values, "skuNum");
            return (Criteria) this;
        }

        public Criteria andSkuNumBetween(Integer value1, Integer value2) {
            addCriterion("sku_num between", value1, value2, "skuNum");
            return (Criteria) this;
        }

        public Criteria andSkuNumNotBetween(Integer value1, Integer value2) {
            addCriterion("sku_num not between", value1, value2, "skuNum");
            return (Criteria) this;
        }

        public Criteria andSkuPriceIsNull() {
            addCriterion("sku_price is null");
            return (Criteria) this;
        }

        public Criteria andSkuPriceIsNotNull() {
            addCriterion("sku_price is not null");
            return (Criteria) this;
        }

        public Criteria andSkuPriceEqualTo(Double value) {
            addCriterion("sku_price =", value, "skuPrice");
            return (Criteria) this;
        }

        public Criteria andSkuPriceNotEqualTo(Double value) {
            addCriterion("sku_price <>", value, "skuPrice");
            return (Criteria) this;
        }

        public Criteria andSkuPriceGreaterThan(Double value) {
            addCriterion("sku_price >", value, "skuPrice");
            return (Criteria) this;
        }

        public Criteria andSkuPriceGreaterThanOrEqualTo(Double value) {
            addCriterion("sku_price >=", value, "skuPrice");
            return (Criteria) this;
        }

        public Criteria andSkuPriceLessThan(Double value) {
            addCriterion("sku_price <", value, "skuPrice");
            return (Criteria) this;
        }

        public Criteria andSkuPriceLessThanOrEqualTo(Double value) {
            addCriterion("sku_price <=", value, "skuPrice");
            return (Criteria) this;
        }

        public Criteria andSkuPriceIn(List<Double> values) {
            addCriterion("sku_price in", values, "skuPrice");
            return (Criteria) this;
        }

        public Criteria andSkuPriceNotIn(List<Double> values) {
            addCriterion("sku_price not in", values, "skuPrice");
            return (Criteria) this;
        }

        public Criteria andSkuPriceBetween(Double value1, Double value2) {
            addCriterion("sku_price between", value1, value2, "skuPrice");
            return (Criteria) this;
        }

        public Criteria andSkuPriceNotBetween(Double value1, Double value2) {
            addCriterion("sku_price not between", value1, value2, "skuPrice");
            return (Criteria) this;
        }

        public Criteria andSkuNameIsNull() {
            addCriterion("sku_name is null");
            return (Criteria) this;
        }

        public Criteria andSkuNameIsNotNull() {
            addCriterion("sku_name is not null");
            return (Criteria) this;
        }

        public Criteria andSkuNameEqualTo(String value) {
            addCriterion("sku_name =", value, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameNotEqualTo(String value) {
            addCriterion("sku_name <>", value, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameGreaterThan(String value) {
            addCriterion("sku_name >", value, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameGreaterThanOrEqualTo(String value) {
            addCriterion("sku_name >=", value, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameLessThan(String value) {
            addCriterion("sku_name <", value, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameLessThanOrEqualTo(String value) {
            addCriterion("sku_name <=", value, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameLike(String value) {
            addCriterion("sku_name like", value, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameNotLike(String value) {
            addCriterion("sku_name not like", value, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameIn(List<String> values) {
            addCriterion("sku_name in", values, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameNotIn(List<String> values) {
            addCriterion("sku_name not in", values, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameBetween(String value1, String value2) {
            addCriterion("sku_name between", value1, value2, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameNotBetween(String value1, String value2) {
            addCriterion("sku_name not between", value1, value2, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuLogoIsNull() {
            addCriterion("sku_logo is null");
            return (Criteria) this;
        }

        public Criteria andSkuLogoIsNotNull() {
            addCriterion("sku_logo is not null");
            return (Criteria) this;
        }

        public Criteria andSkuLogoEqualTo(String value) {
            addCriterion("sku_logo =", value, "skuLogo");
            return (Criteria) this;
        }

        public Criteria andSkuLogoNotEqualTo(String value) {
            addCriterion("sku_logo <>", value, "skuLogo");
            return (Criteria) this;
        }

        public Criteria andSkuLogoGreaterThan(String value) {
            addCriterion("sku_logo >", value, "skuLogo");
            return (Criteria) this;
        }

        public Criteria andSkuLogoGreaterThanOrEqualTo(String value) {
            addCriterion("sku_logo >=", value, "skuLogo");
            return (Criteria) this;
        }

        public Criteria andSkuLogoLessThan(String value) {
            addCriterion("sku_logo <", value, "skuLogo");
            return (Criteria) this;
        }

        public Criteria andSkuLogoLessThanOrEqualTo(String value) {
            addCriterion("sku_logo <=", value, "skuLogo");
            return (Criteria) this;
        }

        public Criteria andSkuLogoLike(String value) {
            addCriterion("sku_logo like", value, "skuLogo");
            return (Criteria) this;
        }

        public Criteria andSkuLogoNotLike(String value) {
            addCriterion("sku_logo not like", value, "skuLogo");
            return (Criteria) this;
        }

        public Criteria andSkuLogoIn(List<String> values) {
            addCriterion("sku_logo in", values, "skuLogo");
            return (Criteria) this;
        }

        public Criteria andSkuLogoNotIn(List<String> values) {
            addCriterion("sku_logo not in", values, "skuLogo");
            return (Criteria) this;
        }

        public Criteria andSkuLogoBetween(String value1, String value2) {
            addCriterion("sku_logo between", value1, value2, "skuLogo");
            return (Criteria) this;
        }

        public Criteria andSkuLogoNotBetween(String value1, String value2) {
            addCriterion("sku_logo not between", value1, value2, "skuLogo");
            return (Criteria) this;
        }

        public Criteria andRegionIdIsNull() {
            addCriterion("region_id is null");
            return (Criteria) this;
        }

        public Criteria andRegionIdIsNotNull() {
            addCriterion("region_id is not null");
            return (Criteria) this;
        }

        public Criteria andRegionIdEqualTo(Integer value) {
            addCriterion("region_id =", value, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionIdNotEqualTo(Integer value) {
            addCriterion("region_id <>", value, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionIdGreaterThan(Integer value) {
            addCriterion("region_id >", value, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("region_id >=", value, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionIdLessThan(Integer value) {
            addCriterion("region_id <", value, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionIdLessThanOrEqualTo(Integer value) {
            addCriterion("region_id <=", value, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionIdIn(List<Integer> values) {
            addCriterion("region_id in", values, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionIdNotIn(List<Integer> values) {
            addCriterion("region_id not in", values, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionIdBetween(Integer value1, Integer value2) {
            addCriterion("region_id between", value1, value2, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionIdNotBetween(Integer value1, Integer value2) {
            addCriterion("region_id not between", value1, value2, "regionId");
            return (Criteria) this;
        }

        public Criteria andAttrInfoIsNull() {
            addCriterion("attr_info is null");
            return (Criteria) this;
        }

        public Criteria andAttrInfoIsNotNull() {
            addCriterion("attr_info is not null");
            return (Criteria) this;
        }

        public Criteria andAttrInfoEqualTo(String value) {
            addCriterion("attr_info =", value, "attrInfo");
            return (Criteria) this;
        }

        public Criteria andAttrInfoNotEqualTo(String value) {
            addCriterion("attr_info <>", value, "attrInfo");
            return (Criteria) this;
        }

        public Criteria andAttrInfoGreaterThan(String value) {
            addCriterion("attr_info >", value, "attrInfo");
            return (Criteria) this;
        }

        public Criteria andAttrInfoGreaterThanOrEqualTo(String value) {
            addCriterion("attr_info >=", value, "attrInfo");
            return (Criteria) this;
        }

        public Criteria andAttrInfoLessThan(String value) {
            addCriterion("attr_info <", value, "attrInfo");
            return (Criteria) this;
        }

        public Criteria andAttrInfoLessThanOrEqualTo(String value) {
            addCriterion("attr_info <=", value, "attrInfo");
            return (Criteria) this;
        }

        public Criteria andAttrInfoLike(String value) {
            addCriterion("attr_info like", value, "attrInfo");
            return (Criteria) this;
        }

        public Criteria andAttrInfoNotLike(String value) {
            addCriterion("attr_info not like", value, "attrInfo");
            return (Criteria) this;
        }

        public Criteria andAttrInfoIn(List<String> values) {
            addCriterion("attr_info in", values, "attrInfo");
            return (Criteria) this;
        }

        public Criteria andAttrInfoNotIn(List<String> values) {
            addCriterion("attr_info not in", values, "attrInfo");
            return (Criteria) this;
        }

        public Criteria andAttrInfoBetween(String value1, String value2) {
            addCriterion("attr_info between", value1, value2, "attrInfo");
            return (Criteria) this;
        }

        public Criteria andAttrInfoNotBetween(String value1, String value2) {
            addCriterion("attr_info not between", value1, value2, "attrInfo");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Byte value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Byte value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Byte value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Byte value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Byte value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Byte> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Byte> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Byte value1, Byte value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andGoodsIdIsNull() {
            addCriterion("goods_id is null");
            return (Criteria) this;
        }

        public Criteria andGoodsIdIsNotNull() {
            addCriterion("goods_id is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsIdEqualTo(String value) {
            addCriterion("goods_id =", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdNotEqualTo(String value) {
            addCriterion("goods_id <>", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdGreaterThan(String value) {
            addCriterion("goods_id >", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdGreaterThanOrEqualTo(String value) {
            addCriterion("goods_id >=", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdLessThan(String value) {
            addCriterion("goods_id <", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdLessThanOrEqualTo(String value) {
            addCriterion("goods_id <=", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdLike(String value) {
            addCriterion("goods_id like", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdNotLike(String value) {
            addCriterion("goods_id not like", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdIn(List<String> values) {
            addCriterion("goods_id in", values, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdNotIn(List<String> values) {
            addCriterion("goods_id not in", values, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdBetween(String value1, String value2) {
            addCriterion("goods_id between", value1, value2, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdNotBetween(String value1, String value2) {
            addCriterion("goods_id not between", value1, value2, "goodsId");
            return (Criteria) this;
        }

        public Criteria andSkuIdIsNull() {
            addCriterion("sku_id is null");
            return (Criteria) this;
        }

        public Criteria andSkuIdIsNotNull() {
            addCriterion("sku_id is not null");
            return (Criteria) this;
        }

        public Criteria andSkuIdEqualTo(String value) {
            addCriterion("sku_id =", value, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdNotEqualTo(String value) {
            addCriterion("sku_id <>", value, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdGreaterThan(String value) {
            addCriterion("sku_id >", value, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdGreaterThanOrEqualTo(String value) {
            addCriterion("sku_id >=", value, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdLessThan(String value) {
            addCriterion("sku_id <", value, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdLessThanOrEqualTo(String value) {
            addCriterion("sku_id <=", value, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdLike(String value) {
            addCriterion("sku_id like", value, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdNotLike(String value) {
            addCriterion("sku_id not like", value, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdIn(List<String> values) {
            addCriterion("sku_id in", values, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdNotIn(List<String> values) {
            addCriterion("sku_id not in", values, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdBetween(String value1, String value2) {
            addCriterion("sku_id between", value1, value2, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdNotBetween(String value1, String value2) {
            addCriterion("sku_id not between", value1, value2, "skuId");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("address is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("address is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("address =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("address <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("address >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("address >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("address <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("address <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("address like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("address not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("address in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("address not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("address between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("address not between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andPayCreditImgIsNull() {
            addCriterion("pay_credit_img is null");
            return (Criteria) this;
        }

        public Criteria andPayCreditImgIsNotNull() {
            addCriterion("pay_credit_img is not null");
            return (Criteria) this;
        }

        public Criteria andPayCreditImgEqualTo(String value) {
            addCriterion("pay_credit_img =", value, "payCreditImg");
            return (Criteria) this;
        }

        public Criteria andPayCreditImgNotEqualTo(String value) {
            addCriterion("pay_credit_img <>", value, "payCreditImg");
            return (Criteria) this;
        }

        public Criteria andPayCreditImgGreaterThan(String value) {
            addCriterion("pay_credit_img >", value, "payCreditImg");
            return (Criteria) this;
        }

        public Criteria andPayCreditImgGreaterThanOrEqualTo(String value) {
            addCriterion("pay_credit_img >=", value, "payCreditImg");
            return (Criteria) this;
        }

        public Criteria andPayCreditImgLessThan(String value) {
            addCriterion("pay_credit_img <", value, "payCreditImg");
            return (Criteria) this;
        }

        public Criteria andPayCreditImgLessThanOrEqualTo(String value) {
            addCriterion("pay_credit_img <=", value, "payCreditImg");
            return (Criteria) this;
        }

        public Criteria andPayCreditImgLike(String value) {
            addCriterion("pay_credit_img like", value, "payCreditImg");
            return (Criteria) this;
        }

        public Criteria andPayCreditImgNotLike(String value) {
            addCriterion("pay_credit_img not like", value, "payCreditImg");
            return (Criteria) this;
        }

        public Criteria andPayCreditImgIn(List<String> values) {
            addCriterion("pay_credit_img in", values, "payCreditImg");
            return (Criteria) this;
        }

        public Criteria andPayCreditImgNotIn(List<String> values) {
            addCriterion("pay_credit_img not in", values, "payCreditImg");
            return (Criteria) this;
        }

        public Criteria andPayCreditImgBetween(String value1, String value2) {
            addCriterion("pay_credit_img between", value1, value2, "payCreditImg");
            return (Criteria) this;
        }

        public Criteria andPayCreditImgNotBetween(String value1, String value2) {
            addCriterion("pay_credit_img not between", value1, value2, "payCreditImg");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andKuaidiNameIsNull() {
            addCriterion("kuaidi_name is null");
            return (Criteria) this;
        }

        public Criteria andKuaidiNameIsNotNull() {
            addCriterion("kuaidi_name is not null");
            return (Criteria) this;
        }

        public Criteria andKuaidiNameEqualTo(String value) {
            addCriterion("kuaidi_name =", value, "kuaidiName");
            return (Criteria) this;
        }

        public Criteria andKuaidiNameNotEqualTo(String value) {
            addCriterion("kuaidi_name <>", value, "kuaidiName");
            return (Criteria) this;
        }

        public Criteria andKuaidiNameGreaterThan(String value) {
            addCriterion("kuaidi_name >", value, "kuaidiName");
            return (Criteria) this;
        }

        public Criteria andKuaidiNameGreaterThanOrEqualTo(String value) {
            addCriterion("kuaidi_name >=", value, "kuaidiName");
            return (Criteria) this;
        }

        public Criteria andKuaidiNameLessThan(String value) {
            addCriterion("kuaidi_name <", value, "kuaidiName");
            return (Criteria) this;
        }

        public Criteria andKuaidiNameLessThanOrEqualTo(String value) {
            addCriterion("kuaidi_name <=", value, "kuaidiName");
            return (Criteria) this;
        }

        public Criteria andKuaidiNameLike(String value) {
            addCriterion("kuaidi_name like", value, "kuaidiName");
            return (Criteria) this;
        }

        public Criteria andKuaidiNameNotLike(String value) {
            addCriterion("kuaidi_name not like", value, "kuaidiName");
            return (Criteria) this;
        }

        public Criteria andKuaidiNameIn(List<String> values) {
            addCriterion("kuaidi_name in", values, "kuaidiName");
            return (Criteria) this;
        }

        public Criteria andKuaidiNameNotIn(List<String> values) {
            addCriterion("kuaidi_name not in", values, "kuaidiName");
            return (Criteria) this;
        }

        public Criteria andKuaidiNameBetween(String value1, String value2) {
            addCriterion("kuaidi_name between", value1, value2, "kuaidiName");
            return (Criteria) this;
        }

        public Criteria andKuaidiNameNotBetween(String value1, String value2) {
            addCriterion("kuaidi_name not between", value1, value2, "kuaidiName");
            return (Criteria) this;
        }

        public Criteria andKuaidiOrderIsNull() {
            addCriterion("kuaidi_order is null");
            return (Criteria) this;
        }

        public Criteria andKuaidiOrderIsNotNull() {
            addCriterion("kuaidi_order is not null");
            return (Criteria) this;
        }

        public Criteria andKuaidiOrderEqualTo(String value) {
            addCriterion("kuaidi_order =", value, "kuaidiOrder");
            return (Criteria) this;
        }

        public Criteria andKuaidiOrderNotEqualTo(String value) {
            addCriterion("kuaidi_order <>", value, "kuaidiOrder");
            return (Criteria) this;
        }

        public Criteria andKuaidiOrderGreaterThan(String value) {
            addCriterion("kuaidi_order >", value, "kuaidiOrder");
            return (Criteria) this;
        }

        public Criteria andKuaidiOrderGreaterThanOrEqualTo(String value) {
            addCriterion("kuaidi_order >=", value, "kuaidiOrder");
            return (Criteria) this;
        }

        public Criteria andKuaidiOrderLessThan(String value) {
            addCriterion("kuaidi_order <", value, "kuaidiOrder");
            return (Criteria) this;
        }

        public Criteria andKuaidiOrderLessThanOrEqualTo(String value) {
            addCriterion("kuaidi_order <=", value, "kuaidiOrder");
            return (Criteria) this;
        }

        public Criteria andKuaidiOrderLike(String value) {
            addCriterion("kuaidi_order like", value, "kuaidiOrder");
            return (Criteria) this;
        }

        public Criteria andKuaidiOrderNotLike(String value) {
            addCriterion("kuaidi_order not like", value, "kuaidiOrder");
            return (Criteria) this;
        }

        public Criteria andKuaidiOrderIn(List<String> values) {
            addCriterion("kuaidi_order in", values, "kuaidiOrder");
            return (Criteria) this;
        }

        public Criteria andKuaidiOrderNotIn(List<String> values) {
            addCriterion("kuaidi_order not in", values, "kuaidiOrder");
            return (Criteria) this;
        }

        public Criteria andKuaidiOrderBetween(String value1, String value2) {
            addCriterion("kuaidi_order between", value1, value2, "kuaidiOrder");
            return (Criteria) this;
        }

        public Criteria andKuaidiOrderNotBetween(String value1, String value2) {
            addCriterion("kuaidi_order not between", value1, value2, "kuaidiOrder");
            return (Criteria) this;
        }

        public Criteria andKuaidiPriceIsNull() {
            addCriterion("kuaidi_price is null");
            return (Criteria) this;
        }

        public Criteria andKuaidiPriceIsNotNull() {
            addCriterion("kuaidi_price is not null");
            return (Criteria) this;
        }

        public Criteria andKuaidiPriceEqualTo(Double value) {
            addCriterion("kuaidi_price =", value, "kuaidiPrice");
            return (Criteria) this;
        }

        public Criteria andKuaidiPriceNotEqualTo(Double value) {
            addCriterion("kuaidi_price <>", value, "kuaidiPrice");
            return (Criteria) this;
        }

        public Criteria andKuaidiPriceGreaterThan(Double value) {
            addCriterion("kuaidi_price >", value, "kuaidiPrice");
            return (Criteria) this;
        }

        public Criteria andKuaidiPriceGreaterThanOrEqualTo(Double value) {
            addCriterion("kuaidi_price >=", value, "kuaidiPrice");
            return (Criteria) this;
        }

        public Criteria andKuaidiPriceLessThan(Double value) {
            addCriterion("kuaidi_price <", value, "kuaidiPrice");
            return (Criteria) this;
        }

        public Criteria andKuaidiPriceLessThanOrEqualTo(Double value) {
            addCriterion("kuaidi_price <=", value, "kuaidiPrice");
            return (Criteria) this;
        }

        public Criteria andKuaidiPriceIn(List<Double> values) {
            addCriterion("kuaidi_price in", values, "kuaidiPrice");
            return (Criteria) this;
        }

        public Criteria andKuaidiPriceNotIn(List<Double> values) {
            addCriterion("kuaidi_price not in", values, "kuaidiPrice");
            return (Criteria) this;
        }

        public Criteria andKuaidiPriceBetween(Double value1, Double value2) {
            addCriterion("kuaidi_price between", value1, value2, "kuaidiPrice");
            return (Criteria) this;
        }

        public Criteria andKuaidiPriceNotBetween(Double value1, Double value2) {
            addCriterion("kuaidi_price not between", value1, value2, "kuaidiPrice");
            return (Criteria) this;
        }

        public Criteria andManjianPriceIsNull() {
            addCriterion("manjian_price is null");
            return (Criteria) this;
        }

        public Criteria andManjianPriceIsNotNull() {
            addCriterion("manjian_price is not null");
            return (Criteria) this;
        }

        public Criteria andManjianPriceEqualTo(Double value) {
            addCriterion("manjian_price =", value, "manjianPrice");
            return (Criteria) this;
        }

        public Criteria andManjianPriceNotEqualTo(Double value) {
            addCriterion("manjian_price <>", value, "manjianPrice");
            return (Criteria) this;
        }

        public Criteria andManjianPriceGreaterThan(Double value) {
            addCriterion("manjian_price >", value, "manjianPrice");
            return (Criteria) this;
        }

        public Criteria andManjianPriceGreaterThanOrEqualTo(Double value) {
            addCriterion("manjian_price >=", value, "manjianPrice");
            return (Criteria) this;
        }

        public Criteria andManjianPriceLessThan(Double value) {
            addCriterion("manjian_price <", value, "manjianPrice");
            return (Criteria) this;
        }

        public Criteria andManjianPriceLessThanOrEqualTo(Double value) {
            addCriterion("manjian_price <=", value, "manjianPrice");
            return (Criteria) this;
        }

        public Criteria andManjianPriceIn(List<Double> values) {
            addCriterion("manjian_price in", values, "manjianPrice");
            return (Criteria) this;
        }

        public Criteria andManjianPriceNotIn(List<Double> values) {
            addCriterion("manjian_price not in", values, "manjianPrice");
            return (Criteria) this;
        }

        public Criteria andManjianPriceBetween(Double value1, Double value2) {
            addCriterion("manjian_price between", value1, value2, "manjianPrice");
            return (Criteria) this;
        }

        public Criteria andManjianPriceNotBetween(Double value1, Double value2) {
            addCriterion("manjian_price not between", value1, value2, "manjianPrice");
            return (Criteria) this;
        }

        public Criteria andUserCouponsIdIsNull() {
            addCriterion("user_coupons_id is null");
            return (Criteria) this;
        }

        public Criteria andUserCouponsIdIsNotNull() {
            addCriterion("user_coupons_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserCouponsIdEqualTo(Integer value) {
            addCriterion("user_coupons_id =", value, "userCouponsId");
            return (Criteria) this;
        }

        public Criteria andUserCouponsIdNotEqualTo(Integer value) {
            addCriterion("user_coupons_id <>", value, "userCouponsId");
            return (Criteria) this;
        }

        public Criteria andUserCouponsIdGreaterThan(Integer value) {
            addCriterion("user_coupons_id >", value, "userCouponsId");
            return (Criteria) this;
        }

        public Criteria andUserCouponsIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_coupons_id >=", value, "userCouponsId");
            return (Criteria) this;
        }

        public Criteria andUserCouponsIdLessThan(Integer value) {
            addCriterion("user_coupons_id <", value, "userCouponsId");
            return (Criteria) this;
        }

        public Criteria andUserCouponsIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_coupons_id <=", value, "userCouponsId");
            return (Criteria) this;
        }

        public Criteria andUserCouponsIdIn(List<Integer> values) {
            addCriterion("user_coupons_id in", values, "userCouponsId");
            return (Criteria) this;
        }

        public Criteria andUserCouponsIdNotIn(List<Integer> values) {
            addCriterion("user_coupons_id not in", values, "userCouponsId");
            return (Criteria) this;
        }

        public Criteria andUserCouponsIdBetween(Integer value1, Integer value2) {
            addCriterion("user_coupons_id between", value1, value2, "userCouponsId");
            return (Criteria) this;
        }

        public Criteria andUserCouponsIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_coupons_id not between", value1, value2, "userCouponsId");
            return (Criteria) this;
        }

        public Criteria andCouponsPriceIsNull() {
            addCriterion("coupons_price is null");
            return (Criteria) this;
        }

        public Criteria andCouponsPriceIsNotNull() {
            addCriterion("coupons_price is not null");
            return (Criteria) this;
        }

        public Criteria andCouponsPriceEqualTo(Double value) {
            addCriterion("coupons_price =", value, "couponsPrice");
            return (Criteria) this;
        }

        public Criteria andCouponsPriceNotEqualTo(Double value) {
            addCriterion("coupons_price <>", value, "couponsPrice");
            return (Criteria) this;
        }

        public Criteria andCouponsPriceGreaterThan(Double value) {
            addCriterion("coupons_price >", value, "couponsPrice");
            return (Criteria) this;
        }

        public Criteria andCouponsPriceGreaterThanOrEqualTo(Double value) {
            addCriterion("coupons_price >=", value, "couponsPrice");
            return (Criteria) this;
        }

        public Criteria andCouponsPriceLessThan(Double value) {
            addCriterion("coupons_price <", value, "couponsPrice");
            return (Criteria) this;
        }

        public Criteria andCouponsPriceLessThanOrEqualTo(Double value) {
            addCriterion("coupons_price <=", value, "couponsPrice");
            return (Criteria) this;
        }

        public Criteria andCouponsPriceIn(List<Double> values) {
            addCriterion("coupons_price in", values, "couponsPrice");
            return (Criteria) this;
        }

        public Criteria andCouponsPriceNotIn(List<Double> values) {
            addCriterion("coupons_price not in", values, "couponsPrice");
            return (Criteria) this;
        }

        public Criteria andCouponsPriceBetween(Double value1, Double value2) {
            addCriterion("coupons_price between", value1, value2, "couponsPrice");
            return (Criteria) this;
        }

        public Criteria andCouponsPriceNotBetween(Double value1, Double value2) {
            addCriterion("coupons_price not between", value1, value2, "couponsPrice");
            return (Criteria) this;
        }

        public Criteria andCouponsTypeIsNull() {
            addCriterion("coupons_type is null");
            return (Criteria) this;
        }

        public Criteria andCouponsTypeIsNotNull() {
            addCriterion("coupons_type is not null");
            return (Criteria) this;
        }

        public Criteria andCouponsTypeEqualTo(Integer value) {
            addCriterion("coupons_type =", value, "couponsType");
            return (Criteria) this;
        }

        public Criteria andCouponsTypeNotEqualTo(Integer value) {
            addCriterion("coupons_type <>", value, "couponsType");
            return (Criteria) this;
        }

        public Criteria andCouponsTypeGreaterThan(Integer value) {
            addCriterion("coupons_type >", value, "couponsType");
            return (Criteria) this;
        }

        public Criteria andCouponsTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("coupons_type >=", value, "couponsType");
            return (Criteria) this;
        }

        public Criteria andCouponsTypeLessThan(Integer value) {
            addCriterion("coupons_type <", value, "couponsType");
            return (Criteria) this;
        }

        public Criteria andCouponsTypeLessThanOrEqualTo(Integer value) {
            addCriterion("coupons_type <=", value, "couponsType");
            return (Criteria) this;
        }

        public Criteria andCouponsTypeIn(List<Integer> values) {
            addCriterion("coupons_type in", values, "couponsType");
            return (Criteria) this;
        }

        public Criteria andCouponsTypeNotIn(List<Integer> values) {
            addCriterion("coupons_type not in", values, "couponsType");
            return (Criteria) this;
        }

        public Criteria andCouponsTypeBetween(Integer value1, Integer value2) {
            addCriterion("coupons_type between", value1, value2, "couponsType");
            return (Criteria) this;
        }

        public Criteria andCouponsTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("coupons_type not between", value1, value2, "couponsType");
            return (Criteria) this;
        }

        public Criteria andReduceIntrRateIsNull() {
            addCriterion("reduce_intr_rate is null");
            return (Criteria) this;
        }

        public Criteria andReduceIntrRateIsNotNull() {
            addCriterion("reduce_intr_rate is not null");
            return (Criteria) this;
        }

        public Criteria andReduceIntrRateEqualTo(Double value) {
            addCriterion("reduce_intr_rate =", value, "reduceIntrRate");
            return (Criteria) this;
        }

        public Criteria andReduceIntrRateNotEqualTo(Double value) {
            addCriterion("reduce_intr_rate <>", value, "reduceIntrRate");
            return (Criteria) this;
        }

        public Criteria andReduceIntrRateGreaterThan(Double value) {
            addCriterion("reduce_intr_rate >", value, "reduceIntrRate");
            return (Criteria) this;
        }

        public Criteria andReduceIntrRateGreaterThanOrEqualTo(Double value) {
            addCriterion("reduce_intr_rate >=", value, "reduceIntrRate");
            return (Criteria) this;
        }

        public Criteria andReduceIntrRateLessThan(Double value) {
            addCriterion("reduce_intr_rate <", value, "reduceIntrRate");
            return (Criteria) this;
        }

        public Criteria andReduceIntrRateLessThanOrEqualTo(Double value) {
            addCriterion("reduce_intr_rate <=", value, "reduceIntrRate");
            return (Criteria) this;
        }

        public Criteria andReduceIntrRateIn(List<Double> values) {
            addCriterion("reduce_intr_rate in", values, "reduceIntrRate");
            return (Criteria) this;
        }

        public Criteria andReduceIntrRateNotIn(List<Double> values) {
            addCriterion("reduce_intr_rate not in", values, "reduceIntrRate");
            return (Criteria) this;
        }

        public Criteria andReduceIntrRateBetween(Double value1, Double value2) {
            addCriterion("reduce_intr_rate between", value1, value2, "reduceIntrRate");
            return (Criteria) this;
        }

        public Criteria andReduceIntrRateNotBetween(Double value1, Double value2) {
            addCriterion("reduce_intr_rate not between", value1, value2, "reduceIntrRate");
            return (Criteria) this;
        }

        public Criteria andDeliverTimeIsNull() {
            addCriterion("deliver_time is null");
            return (Criteria) this;
        }

        public Criteria andDeliverTimeIsNotNull() {
            addCriterion("deliver_time is not null");
            return (Criteria) this;
        }

        public Criteria andDeliverTimeEqualTo(Date value) {
            addCriterion("deliver_time =", value, "deliverTime");
            return (Criteria) this;
        }

        public Criteria andDeliverTimeNotEqualTo(Date value) {
            addCriterion("deliver_time <>", value, "deliverTime");
            return (Criteria) this;
        }

        public Criteria andDeliverTimeGreaterThan(Date value) {
            addCriterion("deliver_time >", value, "deliverTime");
            return (Criteria) this;
        }

        public Criteria andDeliverTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("deliver_time >=", value, "deliverTime");
            return (Criteria) this;
        }

        public Criteria andDeliverTimeLessThan(Date value) {
            addCriterion("deliver_time <", value, "deliverTime");
            return (Criteria) this;
        }

        public Criteria andDeliverTimeLessThanOrEqualTo(Date value) {
            addCriterion("deliver_time <=", value, "deliverTime");
            return (Criteria) this;
        }

        public Criteria andDeliverTimeIn(List<Date> values) {
            addCriterion("deliver_time in", values, "deliverTime");
            return (Criteria) this;
        }

        public Criteria andDeliverTimeNotIn(List<Date> values) {
            addCriterion("deliver_time not in", values, "deliverTime");
            return (Criteria) this;
        }

        public Criteria andDeliverTimeBetween(Date value1, Date value2) {
            addCriterion("deliver_time between", value1, value2, "deliverTime");
            return (Criteria) this;
        }

        public Criteria andDeliverTimeNotBetween(Date value1, Date value2) {
            addCriterion("deliver_time not between", value1, value2, "deliverTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table order
     *
     * @mbg.generated do_not_delete_during_merge Fri Jul 05 22:27:27 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table order
     *
     * @mbg.generated Fri Jul 05 22:27:27 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}