package com.gobase.component.bean.mall.order;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class OrderInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_info
     *
     * @mbg.generated Fri Jul 19 00:28:54 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_info
     *
     * @mbg.generated Fri Jul 19 00:28:54 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_info
     *
     * @mbg.generated Fri Jul 19 00:28:54 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Fri Jul 19 00:28:54 CST 2019
     */
    public OrderInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Fri Jul 19 00:28:54 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Fri Jul 19 00:28:54 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Fri Jul 19 00:28:54 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Fri Jul 19 00:28:54 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Fri Jul 19 00:28:54 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Fri Jul 19 00:28:54 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Fri Jul 19 00:28:54 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Fri Jul 19 00:28:54 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Fri Jul 19 00:28:54 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Fri Jul 19 00:28:54 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table order_info
     *
     * @mbg.generated Fri Jul 19 00:28:54 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNull() {
            addCriterion("order_id is null");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNotNull() {
            addCriterion("order_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrderIdEqualTo(String value) {
            addCriterion("order_id =", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotEqualTo(String value) {
            addCriterion("order_id <>", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThan(String value) {
            addCriterion("order_id >", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThanOrEqualTo(String value) {
            addCriterion("order_id >=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThan(String value) {
            addCriterion("order_id <", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThanOrEqualTo(String value) {
            addCriterion("order_id <=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLike(String value) {
            addCriterion("order_id like", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotLike(String value) {
            addCriterion("order_id not like", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdIn(List<String> values) {
            addCriterion("order_id in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotIn(List<String> values) {
            addCriterion("order_id not in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdBetween(String value1, String value2) {
            addCriterion("order_id between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotBetween(String value1, String value2) {
            addCriterion("order_id not between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andRegionIdIsNull() {
            addCriterion("region_id is null");
            return (Criteria) this;
        }

        public Criteria andRegionIdIsNotNull() {
            addCriterion("region_id is not null");
            return (Criteria) this;
        }

        public Criteria andRegionIdEqualTo(Integer value) {
            addCriterion("region_id =", value, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionIdNotEqualTo(Integer value) {
            addCriterion("region_id <>", value, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionIdGreaterThan(Integer value) {
            addCriterion("region_id >", value, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("region_id >=", value, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionIdLessThan(Integer value) {
            addCriterion("region_id <", value, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionIdLessThanOrEqualTo(Integer value) {
            addCriterion("region_id <=", value, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionIdIn(List<Integer> values) {
            addCriterion("region_id in", values, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionIdNotIn(List<Integer> values) {
            addCriterion("region_id not in", values, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionIdBetween(Integer value1, Integer value2) {
            addCriterion("region_id between", value1, value2, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionIdNotBetween(Integer value1, Integer value2) {
            addCriterion("region_id not between", value1, value2, "regionId");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Byte value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Byte value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Byte value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Byte value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Byte value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Byte> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Byte> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Byte value1, Byte value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andGoodsIdIsNull() {
            addCriterion("goods_id is null");
            return (Criteria) this;
        }

        public Criteria andGoodsIdIsNotNull() {
            addCriterion("goods_id is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsIdEqualTo(String value) {
            addCriterion("goods_id =", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdNotEqualTo(String value) {
            addCriterion("goods_id <>", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdGreaterThan(String value) {
            addCriterion("goods_id >", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdGreaterThanOrEqualTo(String value) {
            addCriterion("goods_id >=", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdLessThan(String value) {
            addCriterion("goods_id <", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdLessThanOrEqualTo(String value) {
            addCriterion("goods_id <=", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdLike(String value) {
            addCriterion("goods_id like", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdNotLike(String value) {
            addCriterion("goods_id not like", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdIn(List<String> values) {
            addCriterion("goods_id in", values, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdNotIn(List<String> values) {
            addCriterion("goods_id not in", values, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdBetween(String value1, String value2) {
            addCriterion("goods_id between", value1, value2, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdNotBetween(String value1, String value2) {
            addCriterion("goods_id not between", value1, value2, "goodsId");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andAddressIdIsNull() {
            addCriterion("address_id is null");
            return (Criteria) this;
        }

        public Criteria andAddressIdIsNotNull() {
            addCriterion("address_id is not null");
            return (Criteria) this;
        }

        public Criteria andAddressIdEqualTo(Integer value) {
            addCriterion("address_id =", value, "addressId");
            return (Criteria) this;
        }

        public Criteria andAddressIdNotEqualTo(Integer value) {
            addCriterion("address_id <>", value, "addressId");
            return (Criteria) this;
        }

        public Criteria andAddressIdGreaterThan(Integer value) {
            addCriterion("address_id >", value, "addressId");
            return (Criteria) this;
        }

        public Criteria andAddressIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("address_id >=", value, "addressId");
            return (Criteria) this;
        }

        public Criteria andAddressIdLessThan(Integer value) {
            addCriterion("address_id <", value, "addressId");
            return (Criteria) this;
        }

        public Criteria andAddressIdLessThanOrEqualTo(Integer value) {
            addCriterion("address_id <=", value, "addressId");
            return (Criteria) this;
        }

        public Criteria andAddressIdIn(List<Integer> values) {
            addCriterion("address_id in", values, "addressId");
            return (Criteria) this;
        }

        public Criteria andAddressIdNotIn(List<Integer> values) {
            addCriterion("address_id not in", values, "addressId");
            return (Criteria) this;
        }

        public Criteria andAddressIdBetween(Integer value1, Integer value2) {
            addCriterion("address_id between", value1, value2, "addressId");
            return (Criteria) this;
        }

        public Criteria andAddressIdNotBetween(Integer value1, Integer value2) {
            addCriterion("address_id not between", value1, value2, "addressId");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andKuaidiNameIsNull() {
            addCriterion("kuaidi_name is null");
            return (Criteria) this;
        }

        public Criteria andKuaidiNameIsNotNull() {
            addCriterion("kuaidi_name is not null");
            return (Criteria) this;
        }

        public Criteria andKuaidiNameEqualTo(String value) {
            addCriterion("kuaidi_name =", value, "kuaidiName");
            return (Criteria) this;
        }

        public Criteria andKuaidiNameNotEqualTo(String value) {
            addCriterion("kuaidi_name <>", value, "kuaidiName");
            return (Criteria) this;
        }

        public Criteria andKuaidiNameGreaterThan(String value) {
            addCriterion("kuaidi_name >", value, "kuaidiName");
            return (Criteria) this;
        }

        public Criteria andKuaidiNameGreaterThanOrEqualTo(String value) {
            addCriterion("kuaidi_name >=", value, "kuaidiName");
            return (Criteria) this;
        }

        public Criteria andKuaidiNameLessThan(String value) {
            addCriterion("kuaidi_name <", value, "kuaidiName");
            return (Criteria) this;
        }

        public Criteria andKuaidiNameLessThanOrEqualTo(String value) {
            addCriterion("kuaidi_name <=", value, "kuaidiName");
            return (Criteria) this;
        }

        public Criteria andKuaidiNameLike(String value) {
            addCriterion("kuaidi_name like", value, "kuaidiName");
            return (Criteria) this;
        }

        public Criteria andKuaidiNameNotLike(String value) {
            addCriterion("kuaidi_name not like", value, "kuaidiName");
            return (Criteria) this;
        }

        public Criteria andKuaidiNameIn(List<String> values) {
            addCriterion("kuaidi_name in", values, "kuaidiName");
            return (Criteria) this;
        }

        public Criteria andKuaidiNameNotIn(List<String> values) {
            addCriterion("kuaidi_name not in", values, "kuaidiName");
            return (Criteria) this;
        }

        public Criteria andKuaidiNameBetween(String value1, String value2) {
            addCriterion("kuaidi_name between", value1, value2, "kuaidiName");
            return (Criteria) this;
        }

        public Criteria andKuaidiNameNotBetween(String value1, String value2) {
            addCriterion("kuaidi_name not between", value1, value2, "kuaidiName");
            return (Criteria) this;
        }

        public Criteria andKuaidiOrderIsNull() {
            addCriterion("kuaidi_order is null");
            return (Criteria) this;
        }

        public Criteria andKuaidiOrderIsNotNull() {
            addCriterion("kuaidi_order is not null");
            return (Criteria) this;
        }

        public Criteria andKuaidiOrderEqualTo(String value) {
            addCriterion("kuaidi_order =", value, "kuaidiOrder");
            return (Criteria) this;
        }

        public Criteria andKuaidiOrderNotEqualTo(String value) {
            addCriterion("kuaidi_order <>", value, "kuaidiOrder");
            return (Criteria) this;
        }

        public Criteria andKuaidiOrderGreaterThan(String value) {
            addCriterion("kuaidi_order >", value, "kuaidiOrder");
            return (Criteria) this;
        }

        public Criteria andKuaidiOrderGreaterThanOrEqualTo(String value) {
            addCriterion("kuaidi_order >=", value, "kuaidiOrder");
            return (Criteria) this;
        }

        public Criteria andKuaidiOrderLessThan(String value) {
            addCriterion("kuaidi_order <", value, "kuaidiOrder");
            return (Criteria) this;
        }

        public Criteria andKuaidiOrderLessThanOrEqualTo(String value) {
            addCriterion("kuaidi_order <=", value, "kuaidiOrder");
            return (Criteria) this;
        }

        public Criteria andKuaidiOrderLike(String value) {
            addCriterion("kuaidi_order like", value, "kuaidiOrder");
            return (Criteria) this;
        }

        public Criteria andKuaidiOrderNotLike(String value) {
            addCriterion("kuaidi_order not like", value, "kuaidiOrder");
            return (Criteria) this;
        }

        public Criteria andKuaidiOrderIn(List<String> values) {
            addCriterion("kuaidi_order in", values, "kuaidiOrder");
            return (Criteria) this;
        }

        public Criteria andKuaidiOrderNotIn(List<String> values) {
            addCriterion("kuaidi_order not in", values, "kuaidiOrder");
            return (Criteria) this;
        }

        public Criteria andKuaidiOrderBetween(String value1, String value2) {
            addCriterion("kuaidi_order between", value1, value2, "kuaidiOrder");
            return (Criteria) this;
        }

        public Criteria andKuaidiOrderNotBetween(String value1, String value2) {
            addCriterion("kuaidi_order not between", value1, value2, "kuaidiOrder");
            return (Criteria) this;
        }

        public Criteria andKuaidiPriceIsNull() {
            addCriterion("kuaidi_price is null");
            return (Criteria) this;
        }

        public Criteria andKuaidiPriceIsNotNull() {
            addCriterion("kuaidi_price is not null");
            return (Criteria) this;
        }

        public Criteria andKuaidiPriceEqualTo(Double value) {
            addCriterion("kuaidi_price =", value, "kuaidiPrice");
            return (Criteria) this;
        }

        public Criteria andKuaidiPriceNotEqualTo(Double value) {
            addCriterion("kuaidi_price <>", value, "kuaidiPrice");
            return (Criteria) this;
        }

        public Criteria andKuaidiPriceGreaterThan(Double value) {
            addCriterion("kuaidi_price >", value, "kuaidiPrice");
            return (Criteria) this;
        }

        public Criteria andKuaidiPriceGreaterThanOrEqualTo(Double value) {
            addCriterion("kuaidi_price >=", value, "kuaidiPrice");
            return (Criteria) this;
        }

        public Criteria andKuaidiPriceLessThan(Double value) {
            addCriterion("kuaidi_price <", value, "kuaidiPrice");
            return (Criteria) this;
        }

        public Criteria andKuaidiPriceLessThanOrEqualTo(Double value) {
            addCriterion("kuaidi_price <=", value, "kuaidiPrice");
            return (Criteria) this;
        }

        public Criteria andKuaidiPriceIn(List<Double> values) {
            addCriterion("kuaidi_price in", values, "kuaidiPrice");
            return (Criteria) this;
        }

        public Criteria andKuaidiPriceNotIn(List<Double> values) {
            addCriterion("kuaidi_price not in", values, "kuaidiPrice");
            return (Criteria) this;
        }

        public Criteria andKuaidiPriceBetween(Double value1, Double value2) {
            addCriterion("kuaidi_price between", value1, value2, "kuaidiPrice");
            return (Criteria) this;
        }

        public Criteria andKuaidiPriceNotBetween(Double value1, Double value2) {
            addCriterion("kuaidi_price not between", value1, value2, "kuaidiPrice");
            return (Criteria) this;
        }

        public Criteria andManjianPriceIsNull() {
            addCriterion("manjian_price is null");
            return (Criteria) this;
        }

        public Criteria andManjianPriceIsNotNull() {
            addCriterion("manjian_price is not null");
            return (Criteria) this;
        }

        public Criteria andManjianPriceEqualTo(Double value) {
            addCriterion("manjian_price =", value, "manjianPrice");
            return (Criteria) this;
        }

        public Criteria andManjianPriceNotEqualTo(Double value) {
            addCriterion("manjian_price <>", value, "manjianPrice");
            return (Criteria) this;
        }

        public Criteria andManjianPriceGreaterThan(Double value) {
            addCriterion("manjian_price >", value, "manjianPrice");
            return (Criteria) this;
        }

        public Criteria andManjianPriceGreaterThanOrEqualTo(Double value) {
            addCriterion("manjian_price >=", value, "manjianPrice");
            return (Criteria) this;
        }

        public Criteria andManjianPriceLessThan(Double value) {
            addCriterion("manjian_price <", value, "manjianPrice");
            return (Criteria) this;
        }

        public Criteria andManjianPriceLessThanOrEqualTo(Double value) {
            addCriterion("manjian_price <=", value, "manjianPrice");
            return (Criteria) this;
        }

        public Criteria andManjianPriceIn(List<Double> values) {
            addCriterion("manjian_price in", values, "manjianPrice");
            return (Criteria) this;
        }

        public Criteria andManjianPriceNotIn(List<Double> values) {
            addCriterion("manjian_price not in", values, "manjianPrice");
            return (Criteria) this;
        }

        public Criteria andManjianPriceBetween(Double value1, Double value2) {
            addCriterion("manjian_price between", value1, value2, "manjianPrice");
            return (Criteria) this;
        }

        public Criteria andManjianPriceNotBetween(Double value1, Double value2) {
            addCriterion("manjian_price not between", value1, value2, "manjianPrice");
            return (Criteria) this;
        }

        public Criteria andUserCouponsIdIsNull() {
            addCriterion("user_coupons_id is null");
            return (Criteria) this;
        }

        public Criteria andUserCouponsIdIsNotNull() {
            addCriterion("user_coupons_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserCouponsIdEqualTo(Integer value) {
            addCriterion("user_coupons_id =", value, "userCouponsId");
            return (Criteria) this;
        }

        public Criteria andUserCouponsIdNotEqualTo(Integer value) {
            addCriterion("user_coupons_id <>", value, "userCouponsId");
            return (Criteria) this;
        }

        public Criteria andUserCouponsIdGreaterThan(Integer value) {
            addCriterion("user_coupons_id >", value, "userCouponsId");
            return (Criteria) this;
        }

        public Criteria andUserCouponsIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_coupons_id >=", value, "userCouponsId");
            return (Criteria) this;
        }

        public Criteria andUserCouponsIdLessThan(Integer value) {
            addCriterion("user_coupons_id <", value, "userCouponsId");
            return (Criteria) this;
        }

        public Criteria andUserCouponsIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_coupons_id <=", value, "userCouponsId");
            return (Criteria) this;
        }

        public Criteria andUserCouponsIdIn(List<Integer> values) {
            addCriterion("user_coupons_id in", values, "userCouponsId");
            return (Criteria) this;
        }

        public Criteria andUserCouponsIdNotIn(List<Integer> values) {
            addCriterion("user_coupons_id not in", values, "userCouponsId");
            return (Criteria) this;
        }

        public Criteria andUserCouponsIdBetween(Integer value1, Integer value2) {
            addCriterion("user_coupons_id between", value1, value2, "userCouponsId");
            return (Criteria) this;
        }

        public Criteria andUserCouponsIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_coupons_id not between", value1, value2, "userCouponsId");
            return (Criteria) this;
        }

        public Criteria andCouponsPriceIsNull() {
            addCriterion("coupons_price is null");
            return (Criteria) this;
        }

        public Criteria andCouponsPriceIsNotNull() {
            addCriterion("coupons_price is not null");
            return (Criteria) this;
        }

        public Criteria andCouponsPriceEqualTo(Double value) {
            addCriterion("coupons_price =", value, "couponsPrice");
            return (Criteria) this;
        }

        public Criteria andCouponsPriceNotEqualTo(Double value) {
            addCriterion("coupons_price <>", value, "couponsPrice");
            return (Criteria) this;
        }

        public Criteria andCouponsPriceGreaterThan(Double value) {
            addCriterion("coupons_price >", value, "couponsPrice");
            return (Criteria) this;
        }

        public Criteria andCouponsPriceGreaterThanOrEqualTo(Double value) {
            addCriterion("coupons_price >=", value, "couponsPrice");
            return (Criteria) this;
        }

        public Criteria andCouponsPriceLessThan(Double value) {
            addCriterion("coupons_price <", value, "couponsPrice");
            return (Criteria) this;
        }

        public Criteria andCouponsPriceLessThanOrEqualTo(Double value) {
            addCriterion("coupons_price <=", value, "couponsPrice");
            return (Criteria) this;
        }

        public Criteria andCouponsPriceIn(List<Double> values) {
            addCriterion("coupons_price in", values, "couponsPrice");
            return (Criteria) this;
        }

        public Criteria andCouponsPriceNotIn(List<Double> values) {
            addCriterion("coupons_price not in", values, "couponsPrice");
            return (Criteria) this;
        }

        public Criteria andCouponsPriceBetween(Double value1, Double value2) {
            addCriterion("coupons_price between", value1, value2, "couponsPrice");
            return (Criteria) this;
        }

        public Criteria andCouponsPriceNotBetween(Double value1, Double value2) {
            addCriterion("coupons_price not between", value1, value2, "couponsPrice");
            return (Criteria) this;
        }

        public Criteria andCouponsTypeIsNull() {
            addCriterion("coupons_type is null");
            return (Criteria) this;
        }

        public Criteria andCouponsTypeIsNotNull() {
            addCriterion("coupons_type is not null");
            return (Criteria) this;
        }

        public Criteria andCouponsTypeEqualTo(Integer value) {
            addCriterion("coupons_type =", value, "couponsType");
            return (Criteria) this;
        }

        public Criteria andCouponsTypeNotEqualTo(Integer value) {
            addCriterion("coupons_type <>", value, "couponsType");
            return (Criteria) this;
        }

        public Criteria andCouponsTypeGreaterThan(Integer value) {
            addCriterion("coupons_type >", value, "couponsType");
            return (Criteria) this;
        }

        public Criteria andCouponsTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("coupons_type >=", value, "couponsType");
            return (Criteria) this;
        }

        public Criteria andCouponsTypeLessThan(Integer value) {
            addCriterion("coupons_type <", value, "couponsType");
            return (Criteria) this;
        }

        public Criteria andCouponsTypeLessThanOrEqualTo(Integer value) {
            addCriterion("coupons_type <=", value, "couponsType");
            return (Criteria) this;
        }

        public Criteria andCouponsTypeIn(List<Integer> values) {
            addCriterion("coupons_type in", values, "couponsType");
            return (Criteria) this;
        }

        public Criteria andCouponsTypeNotIn(List<Integer> values) {
            addCriterion("coupons_type not in", values, "couponsType");
            return (Criteria) this;
        }

        public Criteria andCouponsTypeBetween(Integer value1, Integer value2) {
            addCriterion("coupons_type between", value1, value2, "couponsType");
            return (Criteria) this;
        }

        public Criteria andCouponsTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("coupons_type not between", value1, value2, "couponsType");
            return (Criteria) this;
        }

        public Criteria andReduceIntrRateIsNull() {
            addCriterion("reduce_intr_rate is null");
            return (Criteria) this;
        }

        public Criteria andReduceIntrRateIsNotNull() {
            addCriterion("reduce_intr_rate is not null");
            return (Criteria) this;
        }

        public Criteria andReduceIntrRateEqualTo(Double value) {
            addCriterion("reduce_intr_rate =", value, "reduceIntrRate");
            return (Criteria) this;
        }

        public Criteria andReduceIntrRateNotEqualTo(Double value) {
            addCriterion("reduce_intr_rate <>", value, "reduceIntrRate");
            return (Criteria) this;
        }

        public Criteria andReduceIntrRateGreaterThan(Double value) {
            addCriterion("reduce_intr_rate >", value, "reduceIntrRate");
            return (Criteria) this;
        }

        public Criteria andReduceIntrRateGreaterThanOrEqualTo(Double value) {
            addCriterion("reduce_intr_rate >=", value, "reduceIntrRate");
            return (Criteria) this;
        }

        public Criteria andReduceIntrRateLessThan(Double value) {
            addCriterion("reduce_intr_rate <", value, "reduceIntrRate");
            return (Criteria) this;
        }

        public Criteria andReduceIntrRateLessThanOrEqualTo(Double value) {
            addCriterion("reduce_intr_rate <=", value, "reduceIntrRate");
            return (Criteria) this;
        }

        public Criteria andReduceIntrRateIn(List<Double> values) {
            addCriterion("reduce_intr_rate in", values, "reduceIntrRate");
            return (Criteria) this;
        }

        public Criteria andReduceIntrRateNotIn(List<Double> values) {
            addCriterion("reduce_intr_rate not in", values, "reduceIntrRate");
            return (Criteria) this;
        }

        public Criteria andReduceIntrRateBetween(Double value1, Double value2) {
            addCriterion("reduce_intr_rate between", value1, value2, "reduceIntrRate");
            return (Criteria) this;
        }

        public Criteria andReduceIntrRateNotBetween(Double value1, Double value2) {
            addCriterion("reduce_intr_rate not between", value1, value2, "reduceIntrRate");
            return (Criteria) this;
        }

        public Criteria andDeliverTimeIsNull() {
            addCriterion("deliver_time is null");
            return (Criteria) this;
        }

        public Criteria andDeliverTimeIsNotNull() {
            addCriterion("deliver_time is not null");
            return (Criteria) this;
        }

        public Criteria andDeliverTimeEqualTo(Date value) {
            addCriterion("deliver_time =", value, "deliverTime");
            return (Criteria) this;
        }

        public Criteria andDeliverTimeNotEqualTo(Date value) {
            addCriterion("deliver_time <>", value, "deliverTime");
            return (Criteria) this;
        }

        public Criteria andDeliverTimeGreaterThan(Date value) {
            addCriterion("deliver_time >", value, "deliverTime");
            return (Criteria) this;
        }

        public Criteria andDeliverTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("deliver_time >=", value, "deliverTime");
            return (Criteria) this;
        }

        public Criteria andDeliverTimeLessThan(Date value) {
            addCriterion("deliver_time <", value, "deliverTime");
            return (Criteria) this;
        }

        public Criteria andDeliverTimeLessThanOrEqualTo(Date value) {
            addCriterion("deliver_time <=", value, "deliverTime");
            return (Criteria) this;
        }

        public Criteria andDeliverTimeIn(List<Date> values) {
            addCriterion("deliver_time in", values, "deliverTime");
            return (Criteria) this;
        }

        public Criteria andDeliverTimeNotIn(List<Date> values) {
            addCriterion("deliver_time not in", values, "deliverTime");
            return (Criteria) this;
        }

        public Criteria andDeliverTimeBetween(Date value1, Date value2) {
            addCriterion("deliver_time between", value1, value2, "deliverTime");
            return (Criteria) this;
        }

        public Criteria andDeliverTimeNotBetween(Date value1, Date value2) {
            addCriterion("deliver_time not between", value1, value2, "deliverTime");
            return (Criteria) this;
        }

        public Criteria andTotalPriceIsNull() {
            addCriterion("total_price is null");
            return (Criteria) this;
        }

        public Criteria andTotalPriceIsNotNull() {
            addCriterion("total_price is not null");
            return (Criteria) this;
        }

        public Criteria andTotalPriceEqualTo(BigDecimal value) {
            addCriterion("total_price =", value, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceNotEqualTo(BigDecimal value) {
            addCriterion("total_price <>", value, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceGreaterThan(BigDecimal value) {
            addCriterion("total_price >", value, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("total_price >=", value, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceLessThan(BigDecimal value) {
            addCriterion("total_price <", value, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("total_price <=", value, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceIn(List<BigDecimal> values) {
            addCriterion("total_price in", values, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceNotIn(List<BigDecimal> values) {
            addCriterion("total_price not in", values, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("total_price between", value1, value2, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("total_price not between", value1, value2, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andPorderIdIsNull() {
            addCriterion("porder_id is null");
            return (Criteria) this;
        }

        public Criteria andPorderIdIsNotNull() {
            addCriterion("porder_id is not null");
            return (Criteria) this;
        }

        public Criteria andPorderIdEqualTo(String value) {
            addCriterion("porder_id =", value, "porderId");
            return (Criteria) this;
        }

        public Criteria andPorderIdNotEqualTo(String value) {
            addCriterion("porder_id <>", value, "porderId");
            return (Criteria) this;
        }

        public Criteria andPorderIdGreaterThan(String value) {
            addCriterion("porder_id >", value, "porderId");
            return (Criteria) this;
        }

        public Criteria andPorderIdGreaterThanOrEqualTo(String value) {
            addCriterion("porder_id >=", value, "porderId");
            return (Criteria) this;
        }

        public Criteria andPorderIdLessThan(String value) {
            addCriterion("porder_id <", value, "porderId");
            return (Criteria) this;
        }

        public Criteria andPorderIdLessThanOrEqualTo(String value) {
            addCriterion("porder_id <=", value, "porderId");
            return (Criteria) this;
        }

        public Criteria andPorderIdLike(String value) {
            addCriterion("porder_id like", value, "porderId");
            return (Criteria) this;
        }

        public Criteria andPorderIdNotLike(String value) {
            addCriterion("porder_id not like", value, "porderId");
            return (Criteria) this;
        }

        public Criteria andPorderIdIn(List<String> values) {
            addCriterion("porder_id in", values, "porderId");
            return (Criteria) this;
        }

        public Criteria andPorderIdNotIn(List<String> values) {
            addCriterion("porder_id not in", values, "porderId");
            return (Criteria) this;
        }

        public Criteria andPorderIdBetween(String value1, String value2) {
            addCriterion("porder_id between", value1, value2, "porderId");
            return (Criteria) this;
        }

        public Criteria andPorderIdNotBetween(String value1, String value2) {
            addCriterion("porder_id not between", value1, value2, "porderId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table order_info
     *
     * @mbg.generated do_not_delete_during_merge Fri Jul 19 00:28:54 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table order_info
     *
     * @mbg.generated Fri Jul 19 00:28:54 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}