package com.gobase.component.bean.mall.oper;

import java.util.Date;

public class Banner {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner.id
     *
     * @mbg.generated Tue Jun 11 21:26:35 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner.banner_url
     *
     * @mbg.generated Tue Jun 11 21:26:35 CST 2019
     */
    private String bannerUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner.link_url
     *
     * @mbg.generated Tue Jun 11 21:26:35 CST 2019
     */
    private String linkUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner.status
     *
     * @mbg.generated Tue Jun 11 21:26:35 CST 2019
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner.create_time
     *
     * @mbg.generated Tue Jun 11 21:26:35 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner.update_time
     *
     * @mbg.generated Tue Jun 11 21:26:35 CST 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner.id
     *
     * @return the value of banner.id
     *
     * @mbg.generated Tue Jun 11 21:26:35 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner.id
     *
     * @param id the value for banner.id
     *
     * @mbg.generated Tue Jun 11 21:26:35 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner.banner_url
     *
     * @return the value of banner.banner_url
     *
     * @mbg.generated Tue Jun 11 21:26:35 CST 2019
     */
    public String getBannerUrl() {
        return bannerUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner.banner_url
     *
     * @param bannerUrl the value for banner.banner_url
     *
     * @mbg.generated Tue Jun 11 21:26:35 CST 2019
     */
    public void setBannerUrl(String bannerUrl) {
        this.bannerUrl = bannerUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner.link_url
     *
     * @return the value of banner.link_url
     *
     * @mbg.generated Tue Jun 11 21:26:35 CST 2019
     */
    public String getLinkUrl() {
        return linkUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner.link_url
     *
     * @param linkUrl the value for banner.link_url
     *
     * @mbg.generated Tue Jun 11 21:26:35 CST 2019
     */
    public void setLinkUrl(String linkUrl) {
        this.linkUrl = linkUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner.status
     *
     * @return the value of banner.status
     *
     * @mbg.generated Tue Jun 11 21:26:35 CST 2019
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner.status
     *
     * @param status the value for banner.status
     *
     * @mbg.generated Tue Jun 11 21:26:35 CST 2019
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner.create_time
     *
     * @return the value of banner.create_time
     *
     * @mbg.generated Tue Jun 11 21:26:35 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner.create_time
     *
     * @param createTime the value for banner.create_time
     *
     * @mbg.generated Tue Jun 11 21:26:35 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner.update_time
     *
     * @return the value of banner.update_time
     *
     * @mbg.generated Tue Jun 11 21:26:35 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner.update_time
     *
     * @param updateTime the value for banner.update_time
     *
     * @mbg.generated Tue Jun 11 21:26:35 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}